export const LINK_TO_JSON_OBJECT_WITHOUT_ERRORS_ATTRIBUTES = [{
  attributeContributions: [{
    trait: 'color',
    value: 'rgb(0,255,0)',
    contribution: '33.33'
  }, {
    trait: 'hasPipe',
    value: 'false',
    contribution: '33.33'
  }, {
    trait: 'stamina',
    value: '65',
    contribution: '33.33'
  }],
  totalRarity: '3.00',
  NFT: 1
}, {
  attributeContributions: [{
    trait: 'color',
    value: 'rgb(0,255,0)',
    contribution: '33.33'
  }, {
    trait: 'hasPipe',
    value: 'false',
    contribution: '33.33'
  }, {
    trait: 'stamina',
    value: '65',
    contribution: '33.33'
  }],
  totalRarity: '3.00',
  NFT: 2
}, {
  attributeContributions: [{
    trait: 'color',
    value: 'rgb(0,255,0)',
    contribution: '33.33'
  }, {
    trait: 'hasPipe',
    value: 'false',
    contribution: '33.33'
  }, {
    trait: 'stamina',
    value: '65',
    contribution: '33.33'
  }],
  totalRarity: '3.00',
  NFT: 3
}, {
  attributeContributions: [{
    trait: 'color',
    value: 'rgb(0,255,0)',
    contribution: '33.33'
  }, {
    trait: 'hasPipe',
    value: 'false',
    contribution: '33.33'
  }, {
    trait: 'stamina',
    value: '65',
    contribution: '33.33'
  }],
  totalRarity: '3.00',
  NFT: 4
}, {
  attributeContributions: [{
    trait: 'color',
    value: 'rgb(0,255,0)',
    contribution: '33.33'
  }, {
    trait: 'hasPipe',
    value: 'false',
    contribution: '33.33'
  }, {
    trait: 'stamina',
    value: '65',
    contribution: '33.33'
  }],
  totalRarity: '3.00',
  NFT: 5
}];
//# sourceMappingURL=linkToJsonObjectWithoutErrorsAttributes.js.map