import { HederaUsage } from '../../types/estimate-create-collection';
export declare const NUM_NODES = 13;
export declare const CONSTANT_TERM_WEIGHT = 0.2;
export declare const PRICE_PRECISION = 5;
export declare const FEE_SCHEDULE_MULTIPLIER = 1000;
export declare const USD_TO_TINYCENTS = 10000000000;
export declare const DEFAULT_EXPIRATION_TIME = 2160;
export declare const CONSTANTS_FOR_FORMULAE: {
    DURATION_SIZE: number;
    TRANSFER_LIST_SIZE: number;
    BASE_ACCOUNT_SIZE: number;
    BASE_SCHEDULE_SIZE: number;
    STATE_PROOF_SIZE: number;
    STATUS_SIZE: number;
    EXCHANGE_RATE_SIZE: number;
    EXCHANGE_RATE_SET_SIZE: number;
    BALANCE_RESPONSE_SIZE: number;
    LIVEHASH_SIZE: number;
    VERSION_SIZE: number;
    BASE_RECEIPT_SIZE: number;
    BASE_RECORD_SIZE: number;
    MICROPAYMENT_SIZE: number;
    BASE_TX_SIZE: number;
    BASE_CRYPTOCREATE_SIZE: number;
    BASE_FILECREATE_SIZE: number;
    BASE_SCHEDULECREATE_SIZE: number;
    BASE_QUERYHEADER_SIZE: number;
    BASE_QUERYRESPONSE_SIZE: number;
    PROXYACCOUNT_SIZE: number;
    BASE_TXRESPONSE_SIZE: number;
    GASPARAM_SIZE: number;
    BASE_CONTRACTINFO_SIZE: number;
    BASE_FILEINFO_SIZE: number;
    SOLIDITY_ADDRESS_SIZE: number;
    KEY_SIZE: number;
    TX_HASH_SIZE: number;
    TIMESTAMP_SIZE: number;
    ACCOUNT_ID_SIZE: number;
    SIG_SIZE: number;
    HASH_SIZE: number;
    TRANSACTION_ID_SIZE: number;
    FILE_ID_SIZE: number;
    CONTRACT_ID_SIZE: number;
    TOPIC_ID_SIZE: number;
    BASE_TOPIC_SIZE: number;
    RUNNING_HASH_SIZE: number;
    SEQUENCE_NUMBER_SIZE: number;
    BASIC_TOPIC_SIZE: number;
    TOKEN_ID_SIZE: number;
    BASE_TOKEN_SIZE: number;
    BASE_TOKEN_ASSOCIATION_SIZE: number;
    TOKEN_BALANCE_SIZE: number;
    TOKEN_KYC_STATUS_SIZE: number;
    TOKEN_FREEZE_STATUS_SIZE: number;
    TOKEN_MULTIPLIER: number;
    AUTO_ASSOCIATION_CREATE_MULTIPLIER: number;
    AUTO_ASSOCIATION_UPDATE_MULTIPLIER: number;
    MINUTES_3: number;
    HOURS_1: number;
    HOURS_24: number;
    HOURS_25: number;
    SERIAL_NO_SIZE: number;
    NFT_TRANSFER_SIZE: number;
    FIXED_HBAR_FEE_SIZE: number;
    FIXED_HTS_FEE_SIZE: number;
    FRACTIONAL_FEE_SIZE: number;
    ROYALTY_FEE_NO_FALLBACK_SIZE: number;
    ROYALTY_FEE_HBAR_FALLBACK_SIZE: number;
    ROYALTY_FEE_HTS_FALLBACK_SIZE: number;
    BASE_NFT_REPR_SIZE: number;
    CRYPTO_ALLOWANCE_SIZE: number;
    TOKEN_ALLOWANCE_SIZE: number;
    NFT_ALLOWANCE_SIZE: number;
    SERIAL_NUM_SIZE: number;
    CRYPTO_DELETE_ALLOWANCE_SIZE: number;
    TOKEN_DELETE_ALLOWANCE_SIZE: number;
    NFT_DELETE_ALLOWANCE_SIZE: number;
    AUTO_ASSOCIATION_SIZE: number;
    TOKEN_ASSOCIATION_REPR: number;
    BASE_CONTRACT_SIZE: number;
    KV_PAIR_SIZE: number;
    NUM_IMPLICIT_ETH_SIGS: number;
    PRNG_RANGE_SIZE: number;
    PSEUDORANDOM_NUMBER_SIZE: number;
    PSEUDORANDOM_BYTES_SIZE: number;
    FREE_TIER_LIMIT: number;
    FIRST_TIER_PRICE: number;
    REFERENCE_SLOT_LIFETIME: number;
};
export declare const INITIAL_HEDERA_USAGE: HederaUsage;
export declare const FEE_SCHEDULES: {
    CREATE_TOKEN_NON_FUNGIBLE_UNIQUE: {
        node: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
        network: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
        service: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
    };
    CREATE_TOKEN_NON_FUNGIBLE_UNIQUE_WITH_CUSTOM_FEES: {
        node: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
        network: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
        service: {
            constant: number;
            bpt: number;
            vpt: number;
            rbh: number;
            sbh: number;
            gas: number;
            bpr: number;
            sbpr: number;
            min: number;
            max: number;
        };
    };
};
//# sourceMappingURL=fee-tool.d.ts.map